import logo from "@/assets/logo.svg";
import login from "@/assets/app-icon/login.svg";
import eye_outline from "@/assets/app-icon/eye-outline.svg";
import eye_outline_off from "@/assets/app-icon/eye-outline-off.svg";
import check from "@/assets/app-icon/check.svg";
import arrow_left from "@/assets/app-icon/arrow-left.svg";
import notifications from "@/assets/app-icon/notifications.svg";
import home_outlined from "@/assets/app-icon/home-outline.svg";
import shield from "@/assets/app-icon/shield-half.svg";
import person_outlined from "@/assets/app-icon/person-outline.svg";
import business_outlined from "@/assets/app-icon/business-outline.svg";
import flash_outlined from "@/assets/app-icon/flash-outline.svg";
import flash_large from "@/assets/app-icon/flash-outline-large.svg";
import car_outlined from "@/assets/app-icon/car-outline.svg";
import construct_outlined from "@/assets/app-icon/construct-outline.svg";
import easel_outlined from "@/assets/app-icon/easel-outline.svg";
import person_gradient from "@/assets/app-icon/person-gradient.svg";

export const LogoIcon = logo;
export const LoginIcon = login;
export const EyeOutlineIcon = eye_outline;
export const EyeOutlineOffIcon = eye_outline_off;
export const CheckIcon = check;
export const ArrowLeftIcon = arrow_left;
export const NotificationsIcon = notifications;
export const HomeOutlinedIon = home_outlined;
export const ShieldIcon = shield;
export const PersonOutlinedIcon = person_outlined;
export const BusinessOutlinedIcon = business_outlined;
export const FlashOutlinedIcon = flash_outlined;
export const FlashLargeIcon = flash_large;
export const CarOutlinedIcon = car_outlined;
export const ConstructOutlinedIcon = construct_outlined;
export const EaselOutlinedIcon = easel_outlined;
export const PersonGradientIcon = person_gradient;
