import {
  Person,
  PieChart,
  FolderOpen,
  Power,
  People,
  Sync,
  Payment,
} from "@mui/icons-material";

export const dataStatistic = [
  {
    text: "Installateurs partenaires inscrit",
    icon: Person,
    number: 72,
    value: 2,
    income: false,
  },
  {
    text: "Abonnements en cours",
    icon: PieChart,
    price: 261,
    subscription: 22,
    value: 2,
    income: "same",
  },

  {
    text: "Devis réalisés",
    icon: FolderOpen,
    number: 105,
    B2B: "##",
    B2C: "##",
    value: 2,
    income: false,
  },
  {
    text: "Points de charge",
    icon: Power,
    number: 450,
    B2B: "##",
    B2C: "##",
    value: 18,
    income: true,
  },
  {
    text: "Points de charge supervisés",
    icon: People,
    number: 432,
    B2B: "##",
    B2C: "##",
    value: 18,
    income: true,
  },
  {
    text: "Taux de conversion",
    icon: Sync,
    number: 78,
    B2B: "##",
    B2C: "##",
    value: 2,
    income: false,
  },
  {
    text: "Chiffre d’affaires",
    icon: Payment,
    price: 26100,
    B2B: "12 000",
    B2C: "22 045",
    value: 6,
    income: true,
  },
];
