import type { Metadata } from "next";
import { ReduxProviders } from "@/redux/provider";
import { poppins } from "@/utils/font";
import icon from "@/assets/icon.png";
import "./globals.css";

export const metadata: Metadata = {
  title: "Charge-in | Home",
  description: "Generated by create next app",
  icons: { icon: icon.src },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <ReduxProviders>{children}</ReduxProviders>
      </body>
    </html>
  );
}
